# 应用名称
spring:
  application:
    name: demo

# 应用服务 WEB 访问端口
server:
  port: 8080

# 阿里云 OSS 配置
aliyun:
  oss:
    file:
      endPoint: "xxxxxx"
      keyid: "xxxx"
      keysecret: "xxxx"
      bucketname: "xxxx"